apiVersion: v1
kind: Service
metadata:
  name: example-jaeger
  namespace: default
spec:
  type: ClusterIP
  ports:
    - name: example-a
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: example-b
      protocol: TCP
      port: 8081
      targetPort: 8081
  selector:
    app: example-jaeger