apiVersion: v1
kind: Pod
metadata:
  labels:
    app: example-jaeger
  name: example-jaeger-uat
  namespace: default

spec:
  containers:
  - image: slezzlazy/example-jaeger-a:latest
    imagePullPolicy: Always
    name: example-jaeger-a
    ports:
    - containerPort: 8080
      name: example-a
      protocol: TCP
    env:
    - name: JAEGER_ENDPOINT
      value: http://10.0.67.220:14268/api/traces
    - name: SERVICE_FORMATTER
      value: "localhost"
  - image: slezzlazy/example-jaeger-b:latest
    imagePullPolicy: Always
    name: example-jaeger-b
    ports:
    - containerPort: 8081
      name: example-b
      protocol: TCP
    env:
    - name: JAEGER_ENDPOINT
      value: http://10.0.67.220:14268/api/traces

